### ISSUE TITLE
parseAddress()/ ArgumentsParser.swift failed to compile with "swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a"

### ISSUE THREAD

**Issue by tkhuran** [IBM-Bluemix/swift-helloworld#2]
error: value of type 'NSString' has no member 'componentsSeparatedByString'
        let tokens = args[1].bridge().componentsSeparatedByString(":")
                     ~~~~~~~~^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures

**Solution**
let tokens = args[1].bridge().characters.split{$0 == ":"}.map(String.init)

**Comment by tkhuran** [comment]
#if os(Linux)
        let tokens = args[1].bridge().componentsSeparatedByString(":")
        #else
        let tokens = args[1].bridge().characters.split{$0 == ":"}.map(String.init)
        #endif

**Comment by rolivieri** [comment]
@tkhuran - The master branch for this app needed to be kept compatible with a much older version of the Swift binaries (02-08). Now that we have upgraded the installed buildpack on Bluemix, we can now migrate this code to a later version of the binaries, which we just did. We are now at 05-03. Hence, closing this issue.
